apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "maya-dashboard.fullname" . }}-config
  labels: {{- include "maya-dashboard.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
