<?php

declare(strict_types=1);

namespace Database\Seeders\Snapshot;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/** Generado por db:generate-seeders — no editar a mano. */
class NotificationDefinitionsTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('notification_definitions')->insert(
        array (
          0 => 
          array (
            'id' => 1,
            'key' => 'permissions.changed',
            'source_app' => 'maya-authorization',
            'category' => 'event',
            'label' => 'Permisos del usuario modificados',
            'description' => NULL,
            'enabled' => true,
            'default_severity' => 'medium',
            'title_key' => 'notifications.permissions.changed.title',
            'body_key' => 'notifications.permissions.changed.body',
            'url_template' => '/profile',
            'target_app' => 'dashboard',
            'schedule_cron' => NULL,
            'last_evaluated_at' => NULL,
            'audience' => NULL,
            'created_at' => '2026-06-10 16:40:59+00',
            'updated_at' => '2026-06-10 16:40:59+00',
          ),
          1 => 
          array (
            'id' => 2,
            'key' => 'role.assigned',
            'source_app' => 'maya-authorization',
            'category' => 'event',
            'label' => 'Rol asignado',
            'description' => NULL,
            'enabled' => true,
            'default_severity' => 'info',
            'title_key' => 'notifications.role.assigned.title',
            'body_key' => 'notifications.role.assigned.body',
            'url_template' => '/profile',
            'target_app' => 'dashboard',
            'schedule_cron' => NULL,
            'last_evaluated_at' => NULL,
            'audience' => NULL,
            'created_at' => '2026-06-10 16:40:59+00',
            'updated_at' => '2026-06-10 16:40:59+00',
          ),
          2 => 
          array (
            'id' => 3,
            'key' => 'role.revoked',
            'source_app' => 'maya-authorization',
            'category' => 'event',
            'label' => 'Rol revocado',
            'description' => NULL,
            'enabled' => true,
            'default_severity' => 'medium',
            'title_key' => 'notifications.role.revoked.title',
            'body_key' => 'notifications.role.revoked.body',
            'url_template' => '/profile',
            'target_app' => 'dashboard',
            'schedule_cron' => NULL,
            'last_evaluated_at' => NULL,
            'audience' => NULL,
            'created_at' => '2026-06-10 16:40:59+00',
            'updated_at' => '2026-06-10 16:40:59+00',
          ),
          3 => 
          array (
            'id' => 4,
            'key' => 'permission.override_set',
            'source_app' => 'maya-authorization',
            'category' => 'event',
            'label' => 'Permiso concedido (override)',
            'description' => NULL,
            'enabled' => true,
            'default_severity' => 'medium',
            'title_key' => 'notifications.permission.override_set.title',
            'body_key' => 'notifications.permission.override_set.body',
            'url_template' => '/profile',
            'target_app' => 'dashboard',
            'schedule_cron' => NULL,
            'last_evaluated_at' => NULL,
            'audience' => NULL,
            'created_at' => '2026-06-10 16:40:59+00',
            'updated_at' => '2026-06-10 16:40:59+00',
          ),
          4 => 
          array (
            'id' => 5,
            'key' => 'permission.override_removed',
            'source_app' => 'maya-authorization',
            'category' => 'event',
            'label' => 'Override de permiso eliminado',
            'description' => NULL,
            'enabled' => true,
            'default_severity' => 'medium',
            'title_key' => 'notifications.permission.override_removed.title',
            'body_key' => 'notifications.permission.override_removed.body',
            'url_template' => '/profile',
            'target_app' => 'dashboard',
            'schedule_cron' => NULL,
            'last_evaluated_at' => NULL,
            'audience' => NULL,
            'created_at' => '2026-06-10 16:40:59+00',
            'updated_at' => '2026-06-10 16:40:59+00',
          ),
          5 => 
          array (
            'id' => 6,
            'key' => 'role.permissions.changed',
            'source_app' => 'maya-authorization',
            'category' => 'event',
            'label' => 'Permisos de un rol modificados',
            'description' => NULL,
            'enabled' => true,
            'default_severity' => 'medium',
            'title_key' => 'notifications.role.permissions.changed.title',
            'body_key' => 'notifications.role.permissions.changed.body',
            'url_template' => '/profile',
            'target_app' => 'dashboard',
            'schedule_cron' => NULL,
            'last_evaluated_at' => NULL,
            'audience' => NULL,
            'created_at' => '2026-06-10 16:40:59+00',
            'updated_at' => '2026-06-10 16:40:59+00',
          ),
          6 => 
          array (
            'id' => 7,
            'key' => 'document.validation_requested',
            'source_app' => 'maya-dms',
            'category' => 'event',
            'label' => 'Solicitud de validación de documento',
            'description' => NULL,
            'enabled' => true,
            'default_severity' => 'high',
            'title_key' => 'notifications.document.validation_requested.title',
            'body_key' => 'notifications.document.validation_requested.body',
            'url_template' => '/documents/{document_id}',
            'target_app' => 'dms',
            'schedule_cron' => NULL,
            'last_evaluated_at' => NULL,
            'audience' => NULL,
            'created_at' => '2026-06-10 16:40:59+00',
            'updated_at' => '2026-06-10 16:40:59+00',
          ),
          7 => 
          array (
            'id' => 8,
            'key' => 'document.published',
            'source_app' => 'maya-dms',
            'category' => 'event',
            'label' => 'Documento publicado',
            'description' => NULL,
            'enabled' => true,
            'default_severity' => 'info',
            'title_key' => 'notifications.document.published.title',
            'body_key' => 'notifications.document.published.body',
            'url_template' => '/documents/{document_id}',
            'target_app' => 'dms',
            'schedule_cron' => NULL,
            'last_evaluated_at' => NULL,
            'audience' => NULL,
            'created_at' => '2026-06-10 16:40:59+00',
            'updated_at' => '2026-06-10 16:40:59+00',
          ),
          8 => 
          array (
            'id' => 9,
            'key' => 'document.rejected',
            'source_app' => 'maya-dms',
            'category' => 'event',
            'label' => 'Documento rechazado',
            'description' => NULL,
            'enabled' => true,
            'default_severity' => 'high',
            'title_key' => 'notifications.document.rejected.title',
            'body_key' => 'notifications.document.rejected.body',
            'url_template' => '/documents/{document_id}',
            'target_app' => 'dms',
            'schedule_cron' => NULL,
            'last_evaluated_at' => NULL,
            'audience' => NULL,
            'created_at' => '2026-06-10 16:40:59+00',
            'updated_at' => '2026-06-10 16:40:59+00',
          ),
          9 => 
          array (
            'id' => 10,
            'key' => 'template.validation_requested',
            'source_app' => 'maya-dms',
            'category' => 'event',
            'label' => 'Solicitud de validación de plantilla',
            'description' => NULL,
            'enabled' => true,
            'default_severity' => 'high',
            'title_key' => 'notifications.template.validation_requested.title',
            'body_key' => 'notifications.template.validation_requested.body',
            'url_template' => '/templates/{template_id}',
            'target_app' => 'dms',
            'schedule_cron' => NULL,
            'last_evaluated_at' => NULL,
            'audience' => NULL,
            'created_at' => '2026-06-10 16:40:59+00',
            'updated_at' => '2026-06-10 16:40:59+00',
          ),
          10 => 
          array (
            'id' => 11,
            'key' => 'template.rejected',
            'source_app' => 'maya-dms',
            'category' => 'event',
            'label' => 'Plantilla rechazada',
            'description' => NULL,
            'enabled' => true,
            'default_severity' => 'high',
            'title_key' => 'notifications.template.rejected.title',
            'body_key' => 'notifications.template.rejected.body',
            'url_template' => '/templates/{template_id}',
            'target_app' => 'dms',
            'schedule_cron' => NULL,
            'last_evaluated_at' => NULL,
            'audience' => NULL,
            'created_at' => '2026-06-10 16:40:59+00',
            'updated_at' => '2026-06-10 16:40:59+00',
          ),
          11 => 
          array (
            'id' => 12,
            'key' => 'template.published',
            'source_app' => 'maya-dms',
            'category' => 'event',
            'label' => 'Plantilla publicada',
            'description' => NULL,
            'enabled' => true,
            'default_severity' => 'info',
            'title_key' => 'notifications.template.published.title',
            'body_key' => 'notifications.template.published.body',
            'url_template' => '/templates/{template_id}',
            'target_app' => 'dms',
            'schedule_cron' => NULL,
            'last_evaluated_at' => NULL,
            'audience' => NULL,
            'created_at' => '2026-06-10 16:40:59+00',
            'updated_at' => '2026-06-10 16:40:59+00',
          ),
          12 => 
          array (
            'id' => 13,
            'key' => 'template.version.affects_my_document',
            'source_app' => 'maya-dms',
            'category' => 'event',
            'label' => 'Nueva versión de plantilla afecta a tu documento',
            'description' => NULL,
            'enabled' => true,
            'default_severity' => 'medium',
            'title_key' => 'notifications.template.version.affects_my_document.title',
            'body_key' => 'notifications.template.version.affects_my_document.body',
            'url_template' => '/documents/{document_id}',
            'target_app' => 'dms',
            'schedule_cron' => NULL,
            'last_evaluated_at' => NULL,
            'audience' => NULL,
            'created_at' => '2026-06-10 16:40:59+00',
            'updated_at' => '2026-06-10 16:40:59+00',
          ),
          13 => 
          array (
            'id' => 14,
            'key' => 'log.comment_added',
            'source_app' => 'maya-logs',
            'category' => 'event',
            'label' => 'Comentario añadido a un log',
            'description' => NULL,
            'enabled' => true,
            'default_severity' => 'info',
            'title_key' => 'notifications.log.comment_added.title',
            'body_key' => 'notifications.log.comment_added.body',
            'url_template' => '/logs/{log_id}',
            'target_app' => 'logs',
            'schedule_cron' => NULL,
            'last_evaluated_at' => NULL,
            'audience' => NULL,
            'created_at' => '2026-06-10 16:40:59+00',
            'updated_at' => '2026-06-10 16:40:59+00',
          ),
          14 => 
          array (
            'id' => 15,
            'key' => 'attendance.not_clocked_in',
            'source_app' => 'maya-dashboard',
            'category' => 'event',
            'label' => 'Recordatorio de fichaje',
            'description' => 'Al iniciar sesión, si el usuario no ha fichado hoy.',
            'enabled' => true,
            'default_severity' => 'medium',
            'title_key' => 'notifications.attendance.not_clocked_in.title',
            'body_key' => 'notifications.attendance.not_clocked_in.body',
            'url_template' => '/',
            'target_app' => 'dashboard',
            'schedule_cron' => NULL,
            'last_evaluated_at' => NULL,
            'audience' => NULL,
            'created_at' => '2026-06-10 16:40:59+00',
            'updated_at' => '2026-06-10 16:40:59+00',
          ),
          15 => 
          array (
            'id' => 16,
            'key' => 'dms.validation_deadline_approaching',
            'source_app' => 'maya-dms',
            'category' => 'scheduled',
            'label' => 'Fecha límite de validación próxima',
            'description' => 'Documentos cuya fecha de validación final vence en menos de una semana.',
            'enabled' => true,
            'default_severity' => 'high',
            'title_key' => 'notifications.dms.validation_deadline_approaching.title',
            'body_key' => 'notifications.dms.validation_deadline_approaching.body',
            'url_template' => '/documents/{document_id}',
            'target_app' => 'dms',
            'schedule_cron' => '0 7 * * *',
            'last_evaluated_at' => NULL,
            'audience' => NULL,
            'created_at' => '2026-06-10 16:40:59+00',
            'updated_at' => '2026-06-10 16:40:59+00',
          ),
          16 => 
          array (
            'id' => 17,
            'key' => 'dms.pending_validations_threshold',
            'source_app' => 'maya-dms',
            'category' => 'scheduled',
            'label' => 'Demasiados documentos por validar',
            'description' => 'Usuarios con más de N documentos pendientes de validar.',
            'enabled' => true,
            'default_severity' => 'medium',
            'title_key' => 'notifications.dms.pending_validations_threshold.title',
            'body_key' => 'notifications.dms.pending_validations_threshold.body',
            'url_template' => '/documents',
            'target_app' => 'dms',
            'schedule_cron' => '0 7 * * *',
            'last_evaluated_at' => NULL,
            'audience' => NULL,
            'created_at' => '2026-06-10 16:40:59+00',
            'updated_at' => '2026-06-10 16:40:59+00',
          ),
          17 => 
          array (
            'id' => 18,
            'key' => 'logs.error_spike',
            'source_app' => 'maya-logs',
            'category' => 'scheduled',
            'label' => 'Pico de errores críticos',
            'description' => 'Reemplaza la antigua alert_rule de salud (>N logs críticos en una ventana).',
            'enabled' => true,
            'default_severity' => 'critical',
            'title_key' => 'notifications.logs.error_spike.title',
            'body_key' => 'notifications.logs.error_spike.body',
            'url_template' => '/logs',
            'target_app' => 'logs',
            'schedule_cron' => '* * * * *',
            'last_evaluated_at' => NULL,
            'audience' => NULL,
            'created_at' => '2026-06-10 16:40:59+00',
            'updated_at' => '2026-06-10 16:40:59+00',
          ),
        )
        );
    }
}
